auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecyler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h

  # Maximum duration of a timeseries chunk in Memory
  # If timeseries runs for logner than max_chunk_age
  # It will be flushed and create new chunk
  max_chunk_age: 1h

  chunk_target_size: 120000
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2024-03-25
    store: boltdb
    object_storage: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h